[package]
name = "scraper"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
candid = "0.10.17"
ic-cdk = "0.14.2"
ic-cdk-macros = "0.14"
serde = { version = "1.0", features = ["derive"] }

